name       : caja
version    : 1.27.0
release    : 39
source     :
    - https://github.com/mate-desktop/caja/releases/download/v1.27.0/caja-1.27.0.tar.xz : afdbd0ca7f06c84777124793b388ae6ab8c34acb7d34ab7cdbae47e126d883bb
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.mate
summary    : File manager of the MATE Desktop
description: |
    File manager of the MATE Desktop
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libexif)
    - pkgconfig(libnotify)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(shared-mime-info)
    - pkgconfig(sm)
    - pkgconfig(xext)
    - pkgconfig(xrender)
rundeps    :
    - gvfs
setup      : |
    %patch -p1 < $pkgfiles/0001-data-Allow-Caja-to-show-under-most-GTK-desktops.patch
    %reconfigure --disable-static \
        --disable-update-mimedb \
        --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
