name       : caja
version    : 1.22.3
release    : 28
source     :
    - https://github.com/mate-desktop/caja/archive/v1.22.3.tar.gz : 1d1f4fa047ce2a5790478524ab7201b6c3c08c973160beaada4de17a4920063d
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.mate
summary    : File manager of the MATE Desktop
description: |
    File manager of the MATE Desktop
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libexif)
    - pkgconfig(libnotify)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(shared-mime-info)
    - pkgconfig(sm)
    - pkgconfig(xext)
    - pkgconfig(xrender)
    - mate-common
rundeps    :
    - gvfs
setup      : |
    %patch -p1 < $pkgfiles/0001-data-Allow-Caja-to-show-under-most-GTK-desktops.patch
    %autogen --disable-static \
             --disable-update-mimedb \
             --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
