name       : caja
version    : 1.18.5
release    : 15
source     :
    - https://pub.mate-desktop.org/releases/1.18/caja-1.18.5.tar.xz : a0dc034d60d503993b5f83eb4930c99e86bf90d28175810bdd7ddb4df5128dc6
license    :
    - GPL-2.0
    - LGPL-2.0
component  : desktop.mate
summary    : File manager of the MATE Desktop
description: |
    File manager of the MATE Desktop
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(libnotify)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(shared-mime-info)
    - pkgconfig(sm)
    - pkgconfig(unique-3.0)
    - pkgconfig(xext)
    - pkgconfig(xrender)
rundeps    :
    - gvfs
setup      : |
    %apply_patches
    %reconfigure --disable-static \
                 --disable-update-mimedb
build      : |
    %make
install    : |
    %make_install
