name       : caja
version    : 1.20.2
release    : 20
source     :
    - https://pub.mate-desktop.org/releases/1.20/caja-1.20.2.tar.xz : 8d818489f7788eccd41a2695f616d1b9f3a70ab5d41bfa5ebae49813e46d3286
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
component  : desktop.mate
summary    : File manager of the MATE Desktop
description: |
    File manager of the MATE Desktop
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(libnotify)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(shared-mime-info)
    - pkgconfig(sm)
    - pkgconfig(xext)
    - pkgconfig(xrender)
rundeps    :
    - gvfs
setup      : |
    %patch -p1 < $pkgfiles/0001-data-Allow-Caja-to-show-under-most-GTK-desktops.patch
    %reconfigure --disable-static \
                 --disable-update-mimedb
build      : |
    %make
install    : |
    %make_install
