name       : caja
version    : 1.22.0
release    : 24
source     :
    - https://github.com/mate-desktop//caja/archive/v1.22.0.tar.gz : faeb015e9fcc595371e2b719593d82179a428b943371b692cb9fb745333c1b60
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.mate
summary    : File manager of the MATE Desktop
description: |
    File manager of the MATE Desktop
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libexif)
    - pkgconfig(libnotify)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(shared-mime-info)
    - pkgconfig(sm)
    - pkgconfig(xext)
    - pkgconfig(xrender)
    - mate-common
rundeps    :
    - gvfs
setup      : |
    %patch -p1 < $pkgfiles/0001-data-Allow-Caja-to-show-under-most-GTK-desktops.patch
    %autogen --disable-static \
             --disable-update-mimedb \
             --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
