name       : caja
version    : 1.16.0
release    : 3
source     :
    - http://pub.mate-desktop.org/releases/1.16/caja-1.16.0.tar.xz : 4406d114699475d76b8c30a201c5aff941ec950e8d992459bf005db957286802
license    :
    - GPL-2.0
    - LGPL-2.0
component  : desktop.mate
summary    : File manager of the MATE Desktop
description: |
    File manager of the MATE Desktop
builddeps  :
    - pkgconfig(exempi-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(shared-mime-info)
    - pkgconfig(sm)
    - pkgconfig(unique-3.0)
    - pkgconfig(xext)
    - pkgconfig(xrender)
rundeps    :
    - gvfs
setup      : |
    %configure --disable-static --with-gtk=3.0 --disable-update-mimedb
build      : |
    %make
install    : |
    %make_install
